
name: hey_tutor
description: A Flutter app for connecting tutors with students and parents.
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1

  cloudinary_flutter:
  http: ^1.1.0  # Change from 0.13.5 to 1.1.0

  # Firebase Core & Auth
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.0.3
  firebase_storage: ^13.0.3
  image_picker: ^1.2.0
  connectivity_plus: ^6.0.5

  # State Management
  provider: ^6.1.1

  # UI
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.2
  google_fonts: ^6.2.1
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

